In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[5,6,7]])
print(arr)

[[1 2 3]
 [5 6 7]]


In [ ]:
import numpy as np
a=np.array(42)
b=np.array([1,2,3,5,6,7])
c=np.array([[1,2],[4,5],[7,6]])
d=np.array([[[1,4,3],[2,5,7],[3,7,8],[4,4,5]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3
