In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,-1])

10


In [ ]:
import numpy as np
a = np.ones(3, dtype = int)
print("Matrix a", a)
b = np.ones([3, 3], dtype = int)
print("\nMatrix b", b)

Matrix a [1 1 1]

Matrix b [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
import numpy as np


# create array
x = np.array([1,2,3,4,5,1,2,1,1,1])
print("Original array:")
print(x)

print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[1 2 3 4 5 1 2 1 1 1]
Most frequent value in the above array:
1
